<?php
/**
 * Copyright © Q-Solutions Studio: eCommerce Nanobots. All rights reserved.
 *
 * @category    Nanobots
 * @package     Nanobots_AdminLocaleSwitcher
 * @author      Jakub Winkler <jwinkler@qsolutionsstudio.com
 */

use Magento\Backend\Block\Template;

/** @var Template $block */
?>
<div class="locale-placeholder">
    <form id="locale-form" method="POST" action="<?= $block->getUrl('nanobots_adminlocale/user/updateLocale'); ?>">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>"/>
        <div class="admin-locale-options">
            <label>
                <select class="admin-locales" name="admin-locale"></select>
            </label>
            <div id="locale-selection"></div>
        </div>
    </form>
</div>
